#lang brag

program: filename tag
filename: /FILENAME-IDENTIFIER STRING
tag: /TAG-IDENTIFIER TAG-NAME /ARROW-SYMBOL group-properties? childrens? /END-TAG
group-properties: /PROPERTIES-IDENTIFIER /OPEN-GROUP-PROPERTIES-SYMBOL propertie /CLOSE-GROUP-PROPERTIES-SYMBOL
propertie: /OPEN-PROPERTIE-SYMBOL STRING /COMMA STRING /CLOSE-PROPERTIE-SYMBOL (/COMMA propertie)*
childrens: /CHILDREN-IDENTIFIER (tag* | STRING)
